config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :articles_categories
  has_many :categories, through: :articles_categories

  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 5000}
end

app/models/articles_category.rb
# frozen_string_literal: true

class ArticlesCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :articles_categories
  has_many :articles, through: :articles_categories

  validates :name, presence: true,
            uniqueness: true,
            length: {minimum: 3, maximum: 25}
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @curren_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article_id, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
    @articles.reverse
    @articles = Article.paginate(page: params[:page], per_page: 9)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:notice] = "Article deleted."
  end

  private

  def set_article_id
  @article = Article.find(params[:id])
  end

  def article_params
   params.require(:article).permit(:title, :description, category_ids: [])
  end
  
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :destroy, :edit, :update]
  before_action :require_admin, except: [:show, :index]
  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 6)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully."
      redirect_to @category
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
    flash[:notice] = "Category deleted."
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category name updated."
      redirect_to @category
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 12)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = "Only admins can perform that action."
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.paginate(page: params[:page], per_page: 9)
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController< ApplicationController
  before_action :require_logout, only: [:new, :create]
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "logged out."
    redirect_to root_path
  end

  private

  def require_logout
    if current_user != @user
      flash[:alert] = "You need to logout to perform that action."
      redirect_to current_user
    end
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :edit, :update]
  before_action :require_logout, only: [:new, :create]
  before_action :require_same_user, only: [:destroy, :edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 12)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 6)
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Alpha #{@user.username}, you have successfully signed up!"
      redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User information updated."
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to root_path
    flash[:notice] = "User deleted."
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_logout
    if current_user != @user
      flash[:alert] = "You need to logout to perform that action."
      redirect_to current_user
    end
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can't perform that action."
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article_listing.html.erb
<div class="articles-grid">
  <% @articles.each do |article| %>
    <div class="article-card">
      <h6><%= link_to article.title, article_path(article), class: "article-title"%></h6>
      <p class="desc-expanded"><%= article.description.truncate(400) %></p>
      <%= link_to 'View full article', article_path(article), class: "read-more" %>
      <p><%=  time_ago_in_words(article.created_at) %></p>
    </div>
  <% end %>
</div>

app/views/articles/_articles-listing.html.erb
<div class="articles-grid">
  <% @articles.order(id: :desc).each do |article| %>
    <div class="article-card">
      <h6><%= link_to article.title, article_path(article), class: "article-title"%></h6>
      <p class="desc-expanded"><%= article.description.truncate(400) %></p>
      <% if article.categories.any? %>
        <p class="cate-wrap"><%= render article.categories %></p>
      <%  end %>
      <%= link_to 'View full article', article_path(article), class: "read-more" %>
      <p><%=  time_ago_in_words(article.created_at) %></p>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<section id="article-form-shared">
  <%= form_with(model: @article, local: true, class: "article-form-container") do |f| %>
    <div class="article-form-shared-title">
      <strong><%= f.label :title %><br/></strong>
      <%= f.text_field :title, placeholder: "Write Title..." %>
    </div>
    <div class="article-form-shared-desc">
      <strong><%= f.label :description %><br/></strong>
      <%= f.text_area :description, placeholder: "Write Description..." %>
    </div>
    <div class="article-form-shared-ctg">
        <strong><%= f.label :category %><br/></strong>
      <div class="ctg-ch-boxes">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>
          <div class="ctg-ch-box"><%= c.check_box + c.label %></div>
        <% end %>
      </div>
    </div>

    <a>
      <%= f.submit class: "btn-side" %>
    </a>
  <% end %>
</section>

app/views/articles/edit.html.erb
<section id="article-form">
  <div id="section-p1">
    <h1>Edit an article</h1><br>
    <%= render 'form' %>
  </div>
  <a><%= link_to 'Cancel and go back', articles_path, class: "btn-normal" %></a>
</section>

app/views/articles/index.html.erb
<section id="articles">
  <div class="text-main-articles">
    <h1>Articles listing page</h1>
  </div>
  <%= render 'articles-listing' %>
  <div class="apple_pagination">
    <%= will_paginate @articles %>
  </div>
</section>

app/views/articles/new.html.erb
<section id="article-form">
  <div id="section-p1">
    <h1>Create a new article</h1><br>
    <%= render 'form' %>
  </div>
  <a><%= link_to 'Go to articles listing', articles_path, class: "btn-normal" %></a>
</section>

app/views/articles/show.html.erb
<section id="article-show">
  <div class="section-p1">
    <h4><%= @article.title %></h4>
    <% if @article.categories.any? %>
      <div class="cate-wrap"><%= render @article.categories %></div>
    <% end %>
    <p><%= @article.description %></p>
    <% if @article.user %>
      <p>By <%= link_to @article.user.username, @article.user %></p>
    <% end %>
  </div>
  <div class="article-action">
    <a><%= link_to 'Go to articles listing', articles_path, class: "btn-normal" %></a>
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <a><%= link_to 'Edit', edit_article_path(@article), class: "btn-side" %></a>
      <a><%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-side-warning" %></a>
    <% end %>
  </div>
</section>

app/views/categories/_category.html.erb
<span class="category-badge-small"><%= link_to category.name, category_path(category)%></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<div id="sign-card">
  <div class="sign-card-text">
    <h3>Create Category</h3>
    <p>Make your own article category</p>
  </div>
  <div class="sign-card-form">
    <%= form_with(model: @category, class: "users-form-container") do |f| %>
      <div class="category-form-shared-name">
        <%= f.text_field :name, placeholder: "Name" %>
      </div>
      <%= f.submit class: "btn-sign" %>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<section id="sign-body">
  <%= render 'shared/errors', obj: @category %>
  <div id="sign-card">
    <div class="sign-card-text">
      <h3>Edit Category</h3>
      <p>Change category's name</p>
    </div>
    <div class="sign-card-form">
      <%= form_with(model: @category, class: "users-form-container") do |f| %>
        <div class="category-form-shared-name">
          <%= f.text_field :name, placeholder: "Name" %>
        </div>
        <%= f.submit class: "btn-sign" %>
      <% end %>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<section id="users-index-main">
  <h1>Categories</h1>
  <div class="users-grid-main">
    <% @categories.order(id: :desc).each do |category| %>
      <div class="user-grid-card">
        <h3><%= link_to category.name, category_path(category)%></h3>
        <h6><%= pluralize(category.articles.count, "Articles") %></h6>
        <p>Created <%= time_ago_in_words(category.created_at) %> ago</p>
      </div>
    <% end %>
  </div>
</section>
<div class="apple_pagination">
  <%= will_paginate @articles %>
</div>

app/views/categories/new.html.erb
<section id="sign-body">
  <%= render 'shared/errors', obj: @category %>
  <div id="sign-card">
    <div class="sign-card-text">
      <h3>Create Category</h3>
      <p>Make your own article category</p>
    </div>
    <div class="sign-card-form">
      <%= form_with(model: @category, class: "users-form-container") do |f| %>
        <div class="category-form-shared-name">
          <%= f.text_field :name, placeholder: "Name" %>
        </div>
        <%= f.submit value: "Create Category", class: "btn-sign" %>
      <% end %>
    </div>
  </div>
</section>

app/views/categories/show.html.erb
<section id="users-show-main">
  <div class="user-data">
    <h1>Category: <%= @category.name %></h1>
    <div class="user-action">
      <% if logged_in? && (current_user.admin? || @user == current_user) %>
        <%= link_to 'Edit category', edit_category_path(@category), class: "btn-side" %>
        <%= link_to 'Delete category', category_path(@category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-side-warning" %>
      <% end %>
    </div>
  </div>
  <div class="text-main-users">
    <h3>Articles about <%= @category.name %></h3>
  </div>
  <% if @category.articles.any? %>
    <%= render 'articles/articles-listing' %>
  <% else %>
    <p>There is nothing to show</p>
  <% end %>
</section>
<div class="apple_pagination">
  <%= will_paginate @articles %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="created-msg-<%= name == "notice" ? "success" : "fail" %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<section id="search-sec">
  <label>
    <input type="text" placeholder="Search...">
  </label>
</section>

<section id="header">
  <%= link_to 'Alpha', root_path, class: "navbar-brand" %>

  <div>
    <ul id="navbar">
      <% if logged_in? %>
        <li><%= link_to 'Create Article', new_article_path %></li>
      <% end %>
      <li><%= link_to 'Show All Articles', articles_path %></li>
      <% if logged_in? && current_user.admin? %>
        <li><%= link_to 'New Category', new_category_path %></li>
      <% end %>
      <li><%= link_to 'Categories', categories_path %></li>
      <li><%= link_to 'Bloggers', users_path %></li>
      <% if logged_in? %>
        <li class="user-navigation"><%= link_to current_user.username, user_path(current_user) %> <%= gravatar_for current_user, size: 25 %></li>
        <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log In', login_path %></li>
      <% end %>
      <li><a><span class="material-symbols-outlined">search</span></a></li>
    </ul>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <link rel="icon" type="image" href="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <%= yield %>

    <!--<%= render 'shared/footer' %>-->
  </body>
</html>

app/views/pages/_articles-listing.html.erb
<section id="articles">
  <div class="text">
    <h3>Article Updates</h3>
    <h4><%= link_to "View all", articles_path, class: "all-articles"%></h4>
  </div>
  <div class="articles-grid">
    <% @articles.each do |article| %>
      <div class="article-card">
        <h6><%= link_to article.title, article_path(article), class: "article-title"%></h6>
        <p class="desc"><%= article.description %></p>
        <p><%=  article.created_at %></p>
      </div>
    <% end %>
  </div>
</section>

app/views/pages/home.html.erb
<section id="hero">
  <h2>Alpha Blog</h2>

  <div class="items">
    <a><%= image_tag("hero-bg-home.jpg", :alt => "hero") %></a>
    <div class="container">
      <h4>Lorem ipsum</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in orci in sapien aliquet porta id id nulla. Maecenas non magna metus. In vel tristique ligula. Sed sapien quam, dictum eget posuere et, finibus id est. Vestibulum vitae ante nisi. Curabitur feugiat, risus at ultrices elementum, mi neque vulputate metus, vulputate aliquet diam tortor in orci. Mauris augue mauris, iaculis eget tellus nec, tempus pretium dui. Mauris eget risus placerat, dapibus tortor commodo, tincidunt justo. Fusce porta quis lacus sit amet luctus. Proin sodales rhoncus elit eget ultrices. Sed vestibulum erat eget tellus luctus semper. Nulla suscipit, justo sed ultricies imperdiet, ipsum justo rhoncus nulla, sed tempor nisi metus non urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacus magna, gravida et varius nec, facilisis sit amet purus.

        Donec mollis quam enim, sed aliquet risus commodo eu.</p>
      <div class="buttons">
        <%= link_to 'Learn More', 'https://github.com/Nx0dle/AlphaBlog', class: "btn-normal" %>
        <%= link_to 'Sign Up',  signup_path, class: "btn-side" %>
      </div>
    </div>
  </div>
</section>
<section id="home-article-index-short" style="padding-bottom: 100px;">
  <%= render 'shared/articles-listing-home' %>
  <div class="apple_pagination">
    <%= will_paginate @articles %>
  </div>
</section>

app/views/shared/_articles-listing-home.html.erb
<section id="articles">
  <div class="text-side-articles">
    <h3>Article Updates</h3>
    <h4><%= link_to "View all", articles_path, class: "all-articles"%></h4>
  </div>
  <div class="articles-grid">
    <% @articles.order(id: :desc).each do |article| %>
      <div class="article-card">
        <h6><%= link_to article.title, article_path(article), class: "article-title"%></h6>
        <p class="desc"><%= article.description.truncate(150) %></p>
        <%= link_to 'Read more', article_path(article), class: "read-more" %>
        <p><%=  time_ago_in_words(article.created_at) %></p>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_articles-listing.html.erb
<section id="articles">
  <div class="text-side-articles">
    <h3>Article Updates</h3>
    <h4><%= link_to "View all", articles_path, class: "all-articles"%></h4>
  </div>
  <div class="articles-grid">
    <% @articles.each do |article| %>
      <div class="article-card">
        <h6><%= link_to article.title, article_path(article), class: "article-title"%></h6>
        <p class="desc"><%= article.description.truncate(150) %></p>
        <%= link_to 'Read more', article_path(article), class: "read-more" %>
        <p><%=  time_ago_in_words(article.created_at) %></p>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="article-error">
    <h3>The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section id="footer">
  <small>Copiright &copy; <%= link_to 'Nx0dle', "https://github.com/nx0dle", class: "footer-text" %></small>
</section>

app/views/users/edit.erb
<section id="sign-body">
  <%= render 'shared/errors', obj: @user %>
  <div id="sign-card">
    <div class="sign-card-text">
      <h3>Edit profile</h3>
      <p>Change your personal information</p>
    </div>
    <div class="sign-card-form">
      <%= form_with(model: @user, class: "users-form-container") do |f| %>
        <div class="users-form-shared-username">
          <%= f.text_field :username, placeholder: "Username" %>
        </div>
        <div class="users-form-shared-email">
          <%= f.text_field :email, placeholder: "Email" %>
        </div>
        <div class="users-form-shared-pass">
          <%= f.password_field :password, placeholder: "Password" %>
        </div>
        <%= f.submit value: "Save", class: "btn-sign" %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section id="users-index-main">
  <h1>All Bloggers</h1>
  <div class="users-grid-main">
    <% @users.order(id: :desc).each do | user |%>
      <div class="user-grid-card">
        <h3><%= link_to user.username, user %></h3>
        <%= gravatar_for user, size: 150 %>
        <p>Joined in <%= time_ago_in_words(user.created_at) %></p>
      </div>
    <% end %>
  </div>
</section>
<div class="apple_pagination">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<section id="sign-body">
  <%= render 'shared/errors', obj: @user %>
  <div id="sign-card">
    <div class="sign-card-text">
      <h3>Sign up</h3>
      <p>Let's get started with your free account</p>
    </div>
    <div class="sign-card-form">
      <%= form_with(model: @user, class: "users-form-container") do |f| %>
        <div class="users-form-shared-username">
          <%= f.text_field :username, placeholder: "Username" %>
        </div>
        <div class="users-form-shared-email">
          <%= f.text_field :email, placeholder: "Email" %>
        </div>
        <div class="users-form-shared-pass">
          <%= f.password_field :password, placeholder: "Password" %>
        </div>
        <%= f.submit value: "Sign Up", class: "btn-sign" %>
        <small>Already have an account? <%= link_to 'Log In', login_path %></small>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section id="users-show-main">
  <div class="user-data">
    <%= gravatar_for @user, size: 200 %>
    <h1><% if current_user&.admin? && @user == current_user %><strong>(Admin) </strong><% end %><%= @user.username %>'s profile'</h1>
    <div class="user-action">
      <% if logged_in? && (current_user.admin? || @user == current_user) %>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn-side" %>
        <%= link_to 'Delete Profile', user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-side-warning" %>
      <% end %>
    </div>
  </div>
  <div class="text-main-users">
    <h3>Articles written by <%= @user.username %></h3>
  </div>
  <% if !@user.articles.empty? %>
    <%= render 'articles/articles-listing' %>
  <% else %>
    <p>There is nothing to show</p>
  <% end %>
</section>
<div class="apple_pagination">
  <%= will_paginate @articles %>
</div>